//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoMover {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoMover.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定的目标目录不存在！.
        /// </summary>
        internal static string msg_destNotExist {
            get {
                return ResourceManager.GetString("msg_destNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成了！.
        /// </summary>
        internal static string msg_finished {
            get {
                return ResourceManager.GetString("msg_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请重新指定。.
        /// </summary>
        internal static string msg_pleaseSelectAgain {
            get {
                return ResourceManager.GetString("msg_pleaseSelectAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理中止.
        /// </summary>
        internal static string msg_processAborted {
            get {
                return ResourceManager.GetString("msg_processAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标目录不能与源目录重复！.
        /// </summary>
        internal static string msg_srcAndDestShouldNotBeSame {
            get {
                return ResourceManager.GetString("msg_srcAndDestShouldNotBeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定的源目录不存在！.
        /// </summary>
        internal static string msg_srcNotExist {
            get {
                return ResourceManager.GetString("msg_srcNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前:.
        /// </summary>
        internal static string str_current {
            get {
                return ResourceManager.GetString("str_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出错：.
        /// </summary>
        internal static string str_error {
            get {
                return ResourceManager.GetString("str_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改名:.
        /// </summary>
        internal static string str_rename {
            get {
                return ResourceManager.GetString("str_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳过:.
        /// </summary>
        internal static string str_skip {
            get {
                return ResourceManager.GetString("str_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总共:.
        /// </summary>
        internal static string str_total {
            get {
                return ResourceManager.GetString("str_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择存放处理后照片的文件夹.
        /// </summary>
        internal static string tip_pleaseSelectDestinationFolder {
            get {
                return ResourceManager.GetString("tip_pleaseSelectDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择待处理照片所在文件夹.
        /// </summary>
        internal static string tip_pleaseSelectSourceFolder {
            get {
                return ResourceManager.GetString("tip_pleaseSelectSourceFolder", resourceCulture);
            }
        }
    }
}
